### ISSUE TITLE
x-xsrf-token会失效

### ISSUE THREAD

**Issue by jishunzhao** [BennyThink/realXiaoice#1]
现象：
```
curl http://127.0.0.1:6789/chat?text=hello
{"text": "", "debug": "'NoneType' object has no attribute 'split'"}
```
原因：x-xsrf-token 过大概几分钟会失效，具体时间没测试

解决方式：带上cookie去请求`https://m.weibo.cn/api/config`
响应
```
{
    "preferQuickapp": 0,
    "data": {
        "login": true,
        "st": "9b77e8",
        "uid": "3018550843"
    },
    "ok": 1
}
```
信息中的st就是新的x-xsrf-token，替换掉headers.txt中的`x-xsrf-token`即可
我不会python，不然我就改了

**Comment by BennyThink** [comment]
😂😂😂？

**Comment by jishunzhao** [comment]
不懂python

**Comment by BennyThink** [comment]
我记得我处理过这个csrf……

**Comment by jishunzhao** [comment]
我看到你处理的内容了，可能是我使用方式不对？  我也不确定

**Comment by gaowanliang** [comment]
我今天也遇到了这个问题，实际上问题出现在headers.txt的格式上，如果使用Chrome抓包的话，cookie等字样首字母均为小写，而x-xsrf-token也为全小写。用Firefox就是首字母大写的Cookie和全大写的X-XSRF-TOKEN，如果不懂的直接粘贴进去，在
```python
# xiaoice.py:45
cookie_line = __read_headers().get('Cookie').split(':')[-1].strip()
# xiaoice.py:53
old_csrf = old_headers.get('X-XSRF-TOKEN')
```
就会因为找不到Cookie/X-XSRF-TOKEN字段而出现这个问题

**Comment by BennyThink** [comment]
@gaowanliang 
是的，我在readme里说了这点，注意下这里就好啦
![image](https://user-images.githubusercontent.com/14024832/71726592-86be7680-2e72-11ea-8dcb-c0a5dc0dbd9a.png)
