### ISSUE TITLE
更新About中的链接为https://dmesg.app/xiaoice.html

### ISSUE THREAD

**Issue by teaphi** [BennyThink/realXiaoice#10]
更新About中的链接为https://dmesg.app/xiaoice.html

另外这个库真不戳（

咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕咕

**Comment by BennyThink** [comment]
😂哦我的天，还有这种事情……

**Comment by BennyThink** [comment]
等等，我哪里有提到这个链接了？😂你想要我做什么？哪里有about？😂

**Comment by teaphi** [comment]
![Snipaste_2020-12-08_13-33-41.png](https://i.loli.net/2020/12/08/Kl1UTX6eOYwyoB4.png)
:P

**Comment by BennyThink** [comment]
😂原来是这里，感谢，已经更正
