### ISSUE TITLE
请问下从实践上来说这个 cookie 的有效期是多长？

### ISSUE THREAD

**Issue by BelinChung** [BennyThink/realXiaoice#2]
理论上和实践上来说这个 cookie 的有效期是多长呢？

**Comment by BennyThink** [comment]
理论上，cookie有效期我记得应该是一年。实际上，一旦改密码、登出之类的，那么cookie就失效了。
所以建议隐身模式下登录嘛。

**Comment by BelinChung** [comment]
@BennyThink 好非常感谢。
顺带反馈个问题，本人前端，初次接触 Python，昨天机器上装了 Python3.4，貌似一些语法需要要 3.6 才支持，我升级到 3.7 就 OK了，真这样的话，可能 readme 需要强调下依赖哦，Python 安装有些繁琐。

**Comment by BennyThink** [comment]
是的，需要3.5+，因为使用了type annotation。你这3.4也太过分啦！

**Comment by BelinChung** [comment]
哈哈，小前端，yum install python3 默认装的是 3.4，后来我研究了很久觉得应该是语法问题。又重新自己 build 了一个 3.7 的，发现确实是。

**Comment by BennyThink** [comment]
你这得是centos6.1了吧……源里的太老了。
