### ISSUE TITLE
API 获取到最后 2 条消息有误，导致重复对话

### ISSUE THREAD

**Issue by BelinChung** [BennyThink/realXiaoice#3]
经过测试，API 大概率的返回的最后 2 条消息为倒数 第二条 和 第三条，导致 API 返回了 自己最后发送的消息，形成了重复对话
![image](https://user-images.githubusercontent.com/4954264/71052869-a58cef80-2187-11ea-8de2-24450cd481e8.png)

**Comment by BelinChung** [comment]
测试用例：
question: '  今天天气怎么样'
```
response = r.get('data', {}).get('msgs', {})[0]['text']
if response != msg:
   break
time.sleep(random.random())
```
等待回复的判断条件应该是判断该条消息的 sender_id == '5175429989'，因为默认的 msg 会经过微博的处理  trim() 之类的操作。

**Comment by BennyThink** [comment]
稍等晚上回去测试下，看起来似乎可能有这个问题

**Comment by BelinChung** [comment]
好的，我开了一个 PR，先行 fix 了这个问题，还有就是 log 太多了，调试的时候不方便，所以那个 pr 我删了其他一个 log
