### ISSUE TITLE
希望对小冰回复的含有链接的内容进行无关字符的过滤

### ISSUE THREAD

**Issue by BelinChung** [BennyThink/realXiaoice#6]
在进行某些对话时，小冰会以 ”文字 + 链接“ 的形式进行回复，但是微博直接采用 HTML5 的形式进行返回，里面包含了”<a> <span>“ 等无意义的内容（作为一个正经的API，此字段直接返回HTML，不敢苟同），希望我们的接口更加纯粹，去除无意义的内容，直接返回 URL，供前端自行处理。

测试用例：
```
{
    "created_at": "Thu Dec 19 13:42:06 +0800 2019",
    "id": "4451207903379802",
    "text": "这里给你一个网址哦:<a href='http:\/\/t.cn\/Aik77VlI' data-hide=''><span class='url-icon'><img style='width: 1rem;height: 1rem' src='\/\/h5.sinaimg.cn\/upload\/2015\/09\/25\/3\/timeline_card_small_web_default.png'><\/span> <span class='surl-text'>分享链接<\/span><\/a>",
    "recipient_id": 2101557433,
    "recipient_screen_name": "BelinChung",
    "sender_id": 5175429989,
    "sender_screen_name": "小冰"
}
```
期望返回：
```
{
    "text": "这里给你一个网址哦:http://t.cn/Aik77VIl"
}
```
我不是很擅长 python 关于正则这一块的知识，所以开这个 issue

**Comment by BennyThink** [comment]
直接写个正则过滤下应该就可以了，不过我也不知道怎么写。而且有的时候，小冰会一次性说两句话。

**Comment by BelinChung** [comment]
嗯，没想到微博的后端也那么随意，直接 API 返回 HTML，这样兼容性不好，而且也有安全性问题。
我下午试一下，应该2 个正则就可以搞定（先提取出 href 里面链接、再已<a 开头 a/> 结尾对里面的字符串进行空替换）

**Comment by BennyThink** [comment]
还要处理对`/`的转义……哎

**Comment by BennyThink** [comment]
fixed!

**Comment by BelinChung** [comment]
![image](https://user-images.githubusercontent.com/4954264/71236374-c7c66f00-2339-11ea-8bdb-c8bcf3c5fb4a.png)
Resolved! thanks. 👍
