### ISSUE TITLE
关于发送图片和多条消息接收的实现

### ISSUE THREAD

**Issue by mgsky1** [BennyThink/realXiaoice#7]
不知道作者还有没有计划继续更新项目？
我自己先实现了一下这两个功能，思路大概是这样的

## 发送图片
主要分两步，一步是图片上传，上传成功后渣浪会返回一个`fids`，根据这个`fids`再构造文字聊天上传

## 接收多条消息
我看了一下作者的源代码，你是直接获取最后一条，也是最新的那一条消息，实际上，那个链接返回的是一个消息列表，我在你的基础上做了一些拓展。在发送消息的时候记录时间戳，然后消息列表中有一个描述时间的字段，利用这个字段，转换成另外一系列时间戳。根据这两个时间戳，提取在发送消息时间戳之后的消息处理即可。

由于小冰并不是立马会发送消息的（比如发送图片，可能要稍等一会），所以在执行获取消息的函数前，我设置了休眠时间，这个是可调整的。目前是：发送文字消息--休眠1秒，发送图片消息--休眠7秒

## 效果

![](https://xxx.ilovefishc.com/album/202005/12/001322eo8nonwns85om449.jpg)

## 存在的问题

1、有时候会返回空消息（**很想知道为什么会这样，单步调试的时候不会出现**）
2、多条消息有时不能准确获取，比如上面例子中的【照片含糖量】，我试了2次才成功，其实获取多条消息就是在效果和休眠时间之间进行权衡

不知道作者有没有什么好的看法？不知我是否可以发起一个PR？主要考虑代码的修改幅度会比较大..

**Comment by BennyThink** [comment]
PR是极好的！

Martin Huang <notifications@github.com> 于 2020年5月12日周二 00:07写道：

**Comment by mgsky1** [comment]
@BennyThink 已收到Merged邮件！不知作者是否可以将我的Github ID添加进README的Credit列表中。至于Repo的Contributor列表，由于我设置的问题，导致邮箱跟Github无法关联，所以无法加入，第一次没有经验TAT
