### ISSUE TITLE
无法收到向小冰api发送请求的response

### ISSUE THREAD

**Issue by gaowanliang** [BennyThink/realXiaoice#9]
`requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))`

是xiaoice.py 第117行 `r = s.get(RECV, headers=cur_headers).json()`无法收到response导致的

**Comment by BennyThink** [comment]
可能是网络的问题？你再pull最新的代码试试看吧！

**Comment by gaowanliang** [comment]
应该不是网络问题，我重新pull了最新的代码，但是还是一样的情况。原来的时候是一直部署在服务器上的，但是大概在8月的某天就不能用了，在服务器和本地跑，情况都是一样的。可以发出消息，但是无法收到消息，看起来也不是账户问题吧

**Comment by BennyThink** [comment]
我刚刚测试的时候没问题。你再看看是不是cookie不对

高玩梁 <notifications@github.com> 于 2020年10月2日周五 16:13写道：

**Comment by gaowanliang** [comment]
换了cookie，甚至换了账户之后，依然没有效果，本地和服务器上都是如此

**Comment by BennyThink** [comment]
🤔那么按照如下方法排查下吧：

1. `curl -X POST "https://m.weibo.cn/api/chat/list?uid=5175429989&count=10&unfollowing=0"`
2. `pip3 install -U -r requirements.txt` 然后再试试？

**Comment by gaowanliang** [comment]
1是没什么问题的，返回200。库目前都是最新的，也没什么问题，但是错误依旧

**Comment by BennyThink** [comment]
🤔你看，这是什么情况？要不你重新clone试试？

![image](https://user-images.githubusercontent.com/14024832/94912448-401dab80-04da-11eb-8a5e-549fa83a3028.png)

**Comment by gaowanliang** [comment]
感觉又是我的锅了😅，是因为`Content-Length`没删除导致的这个情况，刚才用postman排查了一下，突然看到`Content-Length`这一行了，删除了就没问题了，我觉得这种很无聊的问题，其实直接程序内解决就行了，要不我pr一个？🤣

**Comment by BennyThink** [comment]
你看，

> 复制全部Request Headers中除了Content-Length以外所有行

我不就是懒得pop这个么😂

**Comment by gaowanliang** [comment]
虽然这个问题解决了，但是还有一个问题，需要你稍微改一下，就是:
```
File "*****\xiaoice.py", line 146, in __get_response
    response_message += __remove_bad_html(eachMsg['image']) + '\n'
KeyError: 'image'
```
这里没判断是不是有image导致如果返回的是纯文本就报错咯

**Comment by BennyThink** [comment]
我承认我错了🤣但是只要你重新pull一下就可以啦

高玩梁 <notifications@github.com> 于 2020年10月2日周五 19:16写道：
